apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: cbc6kfwhs-go 
  janus-idp.io/tekton: cbc6kfwhs-go
  backstage.io/kubernetes-id: cbc6kfwhs-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cbc6kfwhs-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml